# Generated by Django 2.2.3 on 2019-07-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('stock_count', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
